apiVersion: v1
stringData:
 password: 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
 username: tersian
kind: Secret
metadata:
 labels:
   credential.sync.jenkins.openshift.io: "true"
 name: git-auth
 namespace: labs-ci-cd
type: kubernetes.io/basic-auth
